from django.urls import path
 
from .views import *

urlpatterns = [
 
   path('admin-login/', AdminLoginView.as_view(), name='admin-login'),
   path('admin-create/', AdminCreateView.as_view(), name='admin-create'),
   path('admins-all/', AdminListView.as_view(), name='admin-list'),
   path('admin/<int:id>/', AdminDetailView.as_view(), name='admin-detail'),
   path('admin-update/<int:pk>/', AdminUpdateView.as_view(), name='admin-update'),
   path('admin-block/<int:pk>/', BlockUnblockAdminView.as_view(), name='toggle-admin-status'),
   path('admin-delete/<int:pk>/', AdminDeleteView.as_view(), name='admin-delete'),
   path('subscriptions-create/', SubscriptionCreateView.as_view(), name='subscription-create'),
   path('subscriptions/', SubscriptionListView.as_view(), name='subscription-list'),
   path('subscriptions/<int:pk>/', SubscriptionDetailView.as_view(), name='subscription-detail'),
   path('subscriptions-update/<int:pk>/', SubscriptionUpdateView.as_view(), name='subscription-update'),
   path('subscriptions-delete/<int:pk>/', SubscriptionDeleteView.as_view(), name='subscription-delete'),
   path('users-create/', UsersCreateView.as_view(), name='request-subscription'),
   path('users/', UsersListView.as_view(), name='users-list'),
   path('users/<int:id>/', UsersDetailView.as_view(), name='users-detail'),
   path('users-update/<int:id>/', UsersUpdateView.as_view(), name='users-update'),
   path('users-delete/<int:id>/', UsersDeleteView.as_view(), name='users-delete'),
   path('user-block/<int:pk>/', BlockUnblockUsersView.as_view(), name='block-unblock-user'),
   path('staff-create/', StaffCreateView.as_view(), name='admin-create'),
   path('staff-all/', StaffListView.as_view(), name='admin-list'),
   path('staff/<int:id>/', StaffDetailView.as_view(), name='admin-detail'),
   path('staff-update/<int:pk>/', StaffUpdateView.as_view(), name='admin-update'),
   path('staff-block/<int:pk>/', BlockUnblockStaffView.as_view(), name='toggle-admin-status'),
   path('staff-delete/<int:pk>/', StaffDeleteView.as_view(), name='admin-delete'),
   path('banking/', BankingListCreateView.as_view(), name='banking-list-create'),
   path('banking/<int:pk>/', BankingDetailView.as_view(), name='banking-detail'),
   path('invoices/', InvoiceListCreateAPIView.as_view(), name='invoice-list-create'),
   path('sales-staff/', SalesStaffListAPIView.as_view(), name='sales-staff-list'),
   path('invoices/<int:invoice_id>/', InvoiceDetailAPIView.as_view(), name='invoice-detail'),
   path('invoices/unpaid/<int:user_id>/', UnpaidInvoicesByUserAPIView.as_view(), name='unpaid-invoices-by-user'),
   path('payments-received/', PaymentReceivedAPIView.as_view(), name='payment-received'), 
   path('payments/', PaymentReceivedListAPIView.as_view(), name='payment-list'), 
   path('payments/<int:pk>/', PaymentReceivedDetailAPIView.as_view(), name='payment-detail'),
   path('payments/update/<int:pk>/', PaymentReceivedUpdateAPIView.as_view(), name='payment-update'),
   path('payments/delete/<int:pk>/', PaymentReceivedDeleteAPIView.as_view(), name='payment-delete'),
   path('vendors/', VendorListCreateAPIView.as_view(), name='vendor-list-create'),  
   path('vendors/<int:pk>/', VendorRetrieveUpdateDeleteAPIView.as_view(), name='vendor-retrieve-update-delete'), 
   path('expenses/', ExpensesListCreateAPIView.as_view(), name='expenses-list-create'),
   path('expenses/<int:pk>/', ExpensesDetailAPIView.as_view(), name='expenses-detail'),
   path('user_count/', UserCountAPIView.as_view(), name='user-count'),
   path('admin_count/', AdminCountAPIView.as_view(), name='user-count'),
   
] 
