# Generated by Django 5.1.4 on 2024-12-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=True, help_text='Rate for the subscription in currency units', max_digits=10, null=True),
        ),
    ]
