# Generated by Django 5.1.4 on 2024-12-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_invoice_amount_invoice_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='lpo_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
