# Generated by Django 5.1.4 on 2024-12-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_alter_invoice_lpo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='quotation_no',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
