# Generated by Django 5.1.4 on 2024-12-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_alter_invoice_quotation_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partially paid', 'Partially Paid')], default='paid', max_length=20),
        ),
    ]
