# Generated by Django 5.1.4 on 2024-12-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='rate',
            field=models.IntegerField(default=True),
        ),
    ]
