# Generated by Django 5.1.4 on 2024-12-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_alter_invoice_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='amount',
            new_name='discount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='sub_total',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage (e.g., 15.25 for 15.25%)', max_digits=5),
        ),
    ]
