# Generated by Django 5.1.4 on 2024-12-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_alter_invoice_discount_alter_invoice_sub_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sub_total',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.IntegerField(default=True),
        ),
    ]
