# Generated by Django 5.1.4 on 2024-12-24 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0014_alter_invoice_discount_alter_invoice_sub_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_received', models.IntegerField(default=0)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI')], max_length=255)),
                ('payment_number', models.CharField(blank=True, max_length=11, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('amount_due', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('customer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.users')),
                ('deposit_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.banking')),
                ('invoice_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.invoice')),
            ],
        ),
    ]
