# Generated by Django 5.1.4 on 2024-12-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0015_paymentreceived'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceived',
            name='invoice_amount',
            field=models.IntegerField(default=0),
        ),
    ]
